version: "3.9"

services:
  redis:
    image: redis:6.2.4
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redisdata:/data

  database:
    image: postgres:13.2
    env_file:
      - .env
    ports:
      - "6543:${POSTGRES_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build:
      dockerfile: ./change_checker_go/deploy/Dockerfile
      context: ./
    depends_on:
      - database
      - redis
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - go_cache:/go/pkg/mod

networks:
  default:
    external: true
    name: notion_service

volumes:
  go_cache:
