// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Notion API
//
//  API notion 42
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//  Contact:
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
