FROM golang:1.19.1

ENV CGO_ENABLED off

RUN apt-get update && apt-get install -y ca-certificates

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s

CMD air -c /go/src/gitlab.42paris.fr/notion_service/.air-api.toml
