// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Database is the predicate function for database builders.
type Database func(*sql.Selector)

// Status is the predicate function for status builders.
type Status func(*sql.Selector)
