// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ComputorDef computor def
//
// swagger:model computorDef
type ComputorDef struct {

	// bios date
	// Example: 2012
	BiosDate string `json:"bios_date,omitempty"`

	// down
	// Example: false
	Down string `json:"down,omitempty"`

	// hostname
	// Example: e1r1p1
	Hostname string `json:"hostname,omitempty"`

	// ip
	// Example: 10.0.0.0
	IP string `json:"ip,omitempty"`

	// last redump
	// Example: lun. 19 déc. 2022 15:42:10 CET
	LastRedump string `json:"last_redump,omitempty"`

	// mac address
	// Example: e1:e1:e1:e1:e1:e1
	MacAddress string `json:"mac_address,omitempty"`

	// manufacturer
	// Example: Apple Inc.
	Manufacturer string `json:"manufacturer,omitempty"`

	// model
	// Example: Apple 12
	Model string `json:"model,omitempty"`

	// serial
	// Example: COUCOUJESUISUNSERIAL
	Serial string `json:"serial,omitempty"`
}

// Validate validates this computor def
func (m *ComputorDef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this computor def based on context it is used
func (m *ComputorDef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ComputorDef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComputorDef) UnmarshalBinary(b []byte) error {
	var res ComputorDef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
